version: "3.8"

services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: excalidraw
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - excalidraw-net

networks:
  excalidraw-net:
    driver: bridge